name: Run Selenium Tests

on:
  push:
    branches:
      - main
      - develop
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run develop-only tests
        if: github.ref == 'refs/heads/develop'
        run: |
          pytest -m test

      - name: Run test-only tests
        if: github.ref == 'refs/heads/test'
        run: |
          pytest -m test